[Feature] OAuth Interface 구현
mash-up-kr/YourName-iOS pull request #7
Opened 2021-09-12 12:46 UTC by SongSeoYoung

<h3>Related Issue</h3>

- related issue: none

<h3>What does this PR do?</h3>

<br/>

- OAuth 인증방식에서 필요한 interface 를 구현했습니다.
- 이 프로토콜을 채택하고있는 객체 모두 login, logout, authorize가 필요하다고 판단되어 함수를 정의해두었습니다.
- `OAuth.swift`
- `authorize` : 토큰을 가지고있는지 체크하는 함수
- `logIn` : 로그인 용으로 `OAuthResponseType.swift` 의 Observable 을 return함
- `logOut` : 로그아웃 용

<br/>

- `OAuthResponseType.swift` 
- accessToken과 refreshToken을 가지고있는 타입입니다. 이후 필요한 정보들을 추가하여 사용하면 좋을 것 같아 만들어두었습니다!

리뷰 이후 이 인터페이스를 이용해서 AppleLogin과 KakaoLogin 구현하겠습니당!~

2021-09-12 15:45 UTC, O-O-wl requested changes

2021-09-12 15:45 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    }
아마 이부분은 Auth 모델이 아닌 다른 부분에서 저장이 되지 않을까요? 
<img width="459" alt="스크린샷 2021-09-13 오전 12 17 43" src="https://user-images.githubusercontent.com/39197978/132993160-6dc8bea7-84e5-40e8-a63d-3e7fa0680abd.png">
아마 저장하게 되면 상위 레이어가 있고
인증 로직만 Auth에 있어도 될 것 같아여 🙇‍♂️

2021-09-12 15:45 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
> +    func authorize() -> Single<OAuthResponseType>
오 적절한 Observable Trait 을 선택하기 위해서 고민하셨군요 !

2021-09-12 15:45 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
> +    func logOut() -> Completable
Auth를 어떻게 처리할 지 고민이 되는데, 
이부분은 논의는 필요할 것 같지만 `OAuth`에서는 유저정보 등의 리소스에 대한 인가를 해줄 것 같아요.
OAuth에서는 리소스서버(Kakao)로 부터 인가 받았다는 증거로 AccessToken을 모바일 클라이언트에서 클라이언트 서버(너의이름은 백엔드)에 전달해서 검증 후 로그인 처리가 될 것 같아요 .
그래서 해당 `logIn`, `logOut`은 OAuth의 영역이 아니지 않을까 싶어요 🙇‍♂️

제가 생각하는 영역에서는 이런 그림이 되지 않을까 싶어요 🤔

<img width="834" alt="스크린샷 2021-09-13 오전 12 44 13" src="https://user-images.githubusercontent.com/39197978/132993980-97974fdc-a0cc-434f-84f4-88e3d4f23fa1.png">

2021-09-12 15:46 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
> +    func logOut() -> Completable
제가 틀릴 수도 있으니 의견 편하게 말해주세여 🙇‍♂️

2021-09-12 15:51 UTC, O-O-wl requested changes

2021-09-12 15:51 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +struct OAuthResponseType {
혹시 Type이라는 네이밍을 붙이는 것을 선호하시나요?
보통 사용해도 protocol일 때 사용했던 것 같은데 `OAuthResponse` 정도의 네이밍도 충분하지 않을까요?

2021-09-12 15:51 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    }
아마 저희 서비스 자체 로그인에 유저를 검증하기 위한 수단으로 OAuth를 사용하게되는 걸 꺼 같아요.
아마 상단에 남긴 플로우를 보면 카카오 / 애플 로그인 인증토큰을 그대로쓰이기 보단 해당 토큰을 통해 인가받은 클라이언트서버(너의이름은 백엔드)에서 검증 후 발급해준 Access Token을 사용, 저장할 것 같은데 이 플로우는 추후 이야기해보기로 하고 일단 토큰을 가져오기만 해볼까요?

2021-09-12 15:51 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    }
아마 이렇게 플로우가 진행되면 refresh token이 필요하지 않게 될수도!?

2021-09-12 16:09 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
> +    func authorize() -> Single<OAuthResponseType>
👍👍👍

2021-09-12 16:11 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
> +    func logOut() -> Completable
저희 서버(너의이름은 서버)에
로그인/아웃 시 애플로그인과 카카오 로그인등 로그인 형태에 따라서 AccessToken을 받은 이후의 로직이 달라지는 경우가 있을 지도 조금 의문이 드네요 🧐

2021-09-13 01:30 UTC, O-O-wl requested changes

2021-09-13 01:30 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    // + 추가 필요한 정보들..?
아마 프로바이더(kakao, apple) 타입 이 있어야할 것 같아요. 
클라이언트서버(너의 이름은 서버)에서 해당 프로바이더를 알아야 식별가능할 것 같아요

2021-09-13 10:44 UTC, SongSeoYoung commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    // + 추가 필요한 정보들..?
넵 이 provider는 필수로 추가하겠습니다.

2021-09-13 10:46 UTC, SongSeoYoung commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +struct OAuthResponseType {
음 그러게요. response는 네이밍 자체로 타입이라고 유추할 수 있겠네요! 수정하겠습니당!

2021-09-13 10:55 UTC, SongSeoYoung commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    }
repository가 개념으로만 이해가가고 정확히는 잘 모르겟네요. 만약 현재 제가 OAuth protocol을 하나 만들고, 인증수단으로만 얘를 사용하게된다면,
OAuth 프로토콜을 따르는 Kakao, Apple 의 authorize 과정을 통해 만들어진 response (현재는 accesstoken, provider 정보 정도겠네여!) 를 AuthRepository 에서 비지니스적 로직을 가공한다. 라고 생각하면될까요?

2021-09-13 10:59 UTC, SongSeoYoung commented on YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
> +    func logOut() -> Completable
저희가 카톡으로 논의했던 (oauth는 access token만 받고, 이후 저희측 서버단에서 access token을 이용한 auth 를 진행) 내용이 올려주는 도표? 그림? UML? 인 것 맞죠? 그렇게되면 말씀하신 것 처럼 login, logout이 빠져도될 것 같네요! 저는 클라에서 다 처리하는 줄 알았어욥..ㅎㅎ ㅠㅠ
잘 이해한건지 체크 부탁드립니당 :-)

2021-09-13 11:01 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/Auth.swift
> +    func logOut() -> Completable
네네 맞아요 !
일단 백엔드랑 논의중이지만 이쪽 방향으로 진행될 것 같아요.
머지하시고 일단 작업하실 지 아니면 백엔드에서 결정된다음 인터페이스 확정된다음 하실 지는 두분이 원하는 쪽으로 결정해서 진행하면 될 것 같아요!

2021-09-13 11:03 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    }
아 레포지토리는 일단 보류해도 될 것 같아요.
OAuth의 책임에서 로컬 저장은 별개로 분리하면 좋겠다는 의견이었어요 그래서 해당 저장 로직은 분리해도 되지 않을까라는 생각이 들었어요

2021-09-13 15:31 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    private let refreshToken: String
저 이부분이 private이면 안될 것도 같아요
이게 모델또는 도메인로직을 가지는 객체인가, 아니면 데이터만 가지고있는 Entity인가를 고려해봐야할 것 같은데 현재상황에서는 Entity에 가까운 것 같아요

2021-09-13 15:45 UTC, SongSeoYoung commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponseType.swift
> +    private let refreshToken: String
음 이거 한 번 더 고민해보고 다시 코멘트 남기도록하겠습니다.

2021-09-14 14:30 UTC, O-O-wl approved these changes

2021-09-14 14:30 UTC, O-O-wl commented on YourName/YourName/Sources/Domain Layer/Auth/AuthResponse.swift
> +enum Provider {
일반적으로 case는 소문자로 작성하는 것 같아요

2021-09-14 14:35 UTC, merged